# Generated by Django 4.2 on 2023-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('barra', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('estoque', models.FloatField()),
            ],
        ),
    ]
